FROM dbatools/sqlinstance
USER root

# Install PowerShell
RUN apt-get update && apt install -y powershell
# install git
RUN apt install -y git

# some cleanup
RUN apt-get autoremove -y \
    && apt-get clean -y

# things for ImportExcel

RUN apt-get -y update \
    && apt-get install -y --no-install-recommends libgdiplus libc6-dev

ENV GIT_PROMPT_START='\033[1;36dbatools>\033[0m\033[0;33m\w\a\033[0m'

# Save command line history
RUN echo "export HISTFILE=/commandhistory/.bash_history" >> "/root/.bashrc" \
    && echo "export PROMPT_COMMAND='history -a'" >> "/root/.bashrc" \
    && mkdir -p /commandhistory \
    && touch /commandhistory/.bash_history

# Install Pester, 4.10.1
SHELL ["/usr/bin/pwsh", "-c"]
RUN $ErrorActionPreference='Stop'; Install-Module -Name Pester -Force -SkipPublisherCheck -MaximumVersion 4.10.1;

# Install PSFramework,dbachecks,posh-git,ImportExcel, Pansies
SHELL ["/usr/bin/pwsh", "-c"]
RUN $ErrorActionPreference='Stop'; Install-Module -Name PSFramework,dbachecks,posh-git,Microsoft.PowerShell.ConsoleGuiTools,ImportExcel,Pansies,pshtml -Force -SkipPublisherCheck;

# Install dbatools prerelease
SHELL ["/usr/bin/pwsh", "-c"]
RUN $ErrorActionPreference='Stop'; Install-Module -Name dbatools -AllowPrerelease -AllowClobber -Force;


# set the dbatools config to not require encryption - change in SMO
SHELL ["/usr/bin/pwsh", "-c"]
RUN Set-DbatoolsConfig -Name sql.connection.trustcert -Value $true -passthru | Register-DbatoolsConfig; Set-DbatoolsConfig -Name sql.connection.encrypt -Value Optional -passthru | Register-DbatoolsConfig

# change server name
SHELL ["/usr/bin/pwsh", "-c"]
RUN Invoke-DbaQuery -SqlInstance localhost -Query "EXEC sp_dropserver @@SERVERNAME; EXEC sp_addserver 'dbatools1', local;"

# Copy Profile
COPY Profile/profile.ps1 /root/.config/powershell/Microsoft.PowerShell_profile.ps1
