FROM mcr.microsoft.com/mssql/server:2022-latest
USER root
# Install PowerShell
RUN apt-get update && apt install -y powershell
# install git
RUN apt install -y git

# some cleanup
RUN apt-get autoremove -y \
    && apt-get clean -y